### ISSUE TITLE
Is it possible to use PHP code or expressions in Yaml?

### ISSUE THREAD

**Issue by cctgteddy** [rock-symphony/rock-symphony#51]
This might be more specifically a question for Symfony/Yaml, but my specific use case is for Rock Symphony. 

I'm migrating a project that was using friendsofsymfony1/symfony1 v1.5.  We utilize PHP expressions in several of our YAML files for environment specific parameters.  We are already using Symfony/Dotenv called from ProjectConfiguration.class.php.

For example, here is a small snip of what we have:

Is there a better recommended way to do this? 
```yaml
# apps/frontend/config/app.yml
all:
  title: <?php echo getenv("APP_TITLE") . "\n" ?>
  module_dir:  <?php echo getenv("MODULE_DIR") . "\n" ?>
```
